language: swift
os: osx

git:
  depth: 1
  
stages:
  - name: test

branches:
  only:
  - master

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      osx_image: xcode11.4
      script:
        - swift package update
        - swift test
